/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package verifier;

import org.medibloc.vc.VerifiableCredentialException;
import org.medibloc.vc.verifiable.VerifiableCredential;
import org.medibloc.vc.verifiable.VerifiablePresentation;

public class App {
    public static void main(String[] args) throws Exception {
        Verifier verifier = new Verifier();

        VerifiablePresentation vp = verifier.getVpFromHolder();
        printVp(vp);
    }

    private static void printVp(VerifiablePresentation vp) throws VerifiableCredentialException {
        System.out.printf("holder: %s\n", vp.getPresentation().getHolder());
        for (VerifiableCredential vc : vp.getPresentation().getVerifiableCredentials()) {
            System.out.print("VC 1\n");
            System.out.printf("issuer: %s\n", vc.getCredential().getIssuer().getId());
            System.out.printf("hospital: %s\n", vc.getCredential().getCredentialSubject().getClaims().get("hospital"));
        }
    }
}
